#!/usr/bin/env python
"""
    Norman Messtorff <normes@normes.org>
    (c) 2014 - 2015
"""
import time
import logging
import argparse
import nagiosplugin
from keynoteapi import keynoteapi, keynotecli


description = """Nagios plugin using KeynoteApi module.
"""

_log = logging.getLogger('nagiosplugin')


class Keynote(nagiosplugin.Resource):
    """Basic usage of KeynoteApi for this Nagios check"""
    def __init__(self, api_key, measurement_slot, https_proxy=None):
        """collect configuration for KeynoteApi class"""
        # init KeynoteApi class
        self.starttime = time.time()
        self.kapi = keynoteapi.KeynoteApi(api_key)
        self.measurement_slot = measurement_slot
        self.timeranges = ['last_five_minute', 'last_fifteen_minute',
                           'last_one_hour', 'last_24_hours']

    def validate_availdata(self, timerange):
        """
        check if the requested time range maps to given availabilities
        and verifies if we get a valid percentage value.

        returns requested availability or None on invalid data
        """
        _log.debug('time range: %s', timerange)

        availabilities = self.kapi.get_avail_data(self.measurement_slot)
        avail_data = availabilities.get(timerange, None)
        if avail_data is not None:
            try:
                avail_data = float(avail_data)
            except ValueError as e:
                _log.debug(e)
                _log.warning(
                    "unable to convert %s/%s/avail_data='%s' to float",
                    self.measurement_slot, timerange, avail_data
                    )

            if not (0 <= avail_data <= 100):
                avail_data = None

        return avail_data

    def validate_perfdata(self, timerange):
        """
        checks if the requested response time is a valid value in seconds

        returns response time or None on invalid data
        """
        _log.debug('time range: %s', timerange)

        performance_data = self.kapi.get_perf_data(self.measurement_slot)
        perf_data = performance_data.get(timerange, None)
        if perf_data is not None:
            try:
                perf_data = float(perf_data)
            except ValueError as e:
                _log.debug(e)
                _log.warning("unable to convert %s/%s/perf_data='%s' to float",
                             self.measurement_slot, timerange, perf_data)

            if not perf_data >= 0:
                perf_data = None

        return perf_data

    def probe(self):
        """
        Iterates over all time ranges and collects metrics for this probe.

        returns one or more metrics
        """
        avail_counter = 0
        perf_counter = 0

        for timerange in self.timeranges:
            # get availability metrics
            avail_data = self.validate_availdata(timerange)
            if avail_data is not None:
                avail_counter += 1
                yield nagiosplugin.Metric(
                    "avail_%s" % self.kapi.timeranges[timerange],
                    avail_data, uom='%', min=0, max=100,
                    context='availability_%s' % timerange)

            # get performance metrics
            perf_data = self.validate_perfdata(timerange)
            if perf_data is not None:
                perf_counter += 1
                yield nagiosplugin.Metric(
                    "response_%s" % self.kapi.timeranges[timerange],
                    perf_data, uom='s', min=0,
                    context='responsetime_%s' % timerange)

        # verify if we got any availability result
        _log.debug('avail_counter: %s', avail_counter)
        if avail_counter == 0:
            calls_left = self.kapi.get_remaining_api_calls()[0]
            raise AttributeError('No availability in time ranges! '
                               '(Keynote Error? %s API calls left this hour)'
                               % ("Unknown number of" if calls_left is None else calls_left))

        # verify if we got any responsetime result
        _log.debug('perf_counter: %s', perf_counter)
        if perf_counter == 0:
            calls_left = self.kapi.get_remaining_api_calls()[0]
            raise AttributeError('No response times in time ranges! '
                               '(Keynote Error? %s API calls left this hour)'
                               % ("Unknown number of" if calls_left is None else calls_left))

        # monitor available API calls to Keynote
        yield nagiosplugin.Metric("remaining_api_calls_hour",
                                  self.kapi.get_remaining_api_calls()[0],
                                  min=0)
        yield nagiosplugin.Metric("remaining_api_calls_day",
                                  self.kapi.get_remaining_api_calls()[1],
                                  min=0)

        # Perfdata for runtime of this check
        yield nagiosplugin.Metric("script_runtime",
                                  time.time()-self.starttime, uom='s', min=0)


class KeynoteSummary(nagiosplugin.Summary):
    """
        Better status lines on check output
    """
    def __init__(self, measurement_slot):
        self.measurement_slot = measurement_slot

    def ok(self, results):
        """Output on OK state"""
        _log.debug('results: %i in %s', len(results), results)

        output = "%s: " % self.measurement_slot
        for item in results:
            output += "%s %s; " % (item.metric.name, item.metric)
        _log.debug('RETURN:: %s', output)
        return output

    def problem(self, results):
        """Output on problem states"""
        _log.debug('results: %i in %s', len(results), results)

        output = "%s: " % self.measurement_slot
        for item in results:
            output += "%s %s %s; " % (item.metric.name,
                                      item.metric,
                                      item.state)
        _log.debug('RETURN:: %s', output)
        return output


@nagiosplugin.guarded
def main():
    argp = argparse.ArgumentParser(description=description)
    argp.add_argument('-v', '--verbose', action='count', default=0,
                      help='enable verbose logging up to 3 times. Default: 0')
    argp.add_argument('-t', '--timeout', type=int, default=10,
                      help='timeout for running this script. Default: 10')
    argp.add_argument('-k', '--apikey', type=str, required=False,
                      help='your personal API key from api.keynote.com')
    argp.add_argument('-p', '--https-proxy',
                      help='HTTPS proxy server (e.g., "proxy.example.com:3128")')
    argp.add_argument('-l', '--list-measurement-slots', action='store_true',
                      help='list all available measurement slots and its'
                           ' current data values')
    argp.add_argument('-m', '--measurement-slot', type=str, required=True,
                      help='measurement of your Keynote account to monitor')
    argp.add_argument('-a', '--avail-warning', metavar='RANGE', default='99:',
                      help='warning level for any time range of availabilites'
                      '. Default: \'99:\'')
    argp.add_argument('-A', '--avail-critical', metavar='RANGE', default='80:',
                      help='critical level for any time range of availabilites'
                      '. Default: \'80:\'')
    argp.add_argument('-r', '--response-warning', metavar='RANGE',
                      help='warning level for any time range of response times')
    argp.add_argument('-R', '--response-critical', metavar='RANGE',
                      help='critical level for any time range of response times')
    argp.add_argument('--apicalls-hour-warning', metavar='RANGE',
                      default='250:', help='warning level for any time range of'
                      ' response times. Default: \'250:\'')
    argp.add_argument('--apicalls-hour-critical', metavar='RANGE', default='',
                      help='critical level for any time range of response times')
    argp.add_argument('--apicalls-day-warning', metavar='RANGE',
                      default='6000:', help='warning level for any time range '
                      'of response times. Default: \'6000:\'')
    argp.add_argument('--apicalls-day-critical', metavar='RANGE', default='',
                      help='critical level for any time range of response times')
    args = argp.parse_args()

    # #TODO to be solved by an own ArgumentParser.Action later
    if args.list_measurement_slots:
        kcli = keynotecli.KeynoteCli(args.apikey)
        kcli.listMeasurements()
        exit(0)

    check = nagiosplugin.Check(
        Keynote(api_key=args.apikey, measurement_slot=args.measurement_slot,
                https_proxy=args.https_proxy),
        nagiosplugin.ScalarContext('availability_last_five_minute',
                                   args.avail_warning, args.avail_critical),
        nagiosplugin.ScalarContext('availability_last_fifteen_minute',
                                   args.avail_warning, args.avail_critical),
        nagiosplugin.ScalarContext('availability_last_one_hour',
                                   args.avail_warning, args.avail_critical),
        nagiosplugin.ScalarContext('availability_last_24_hours',
                                   args.avail_warning, args.avail_critical),
        nagiosplugin.ScalarContext('responsetime_last_five_minute',
                                   args.response_warning,
                                   args.response_critical),
        nagiosplugin.ScalarContext('responsetime_last_fifteen_minute',
                                   args.response_warning,
                                   args.response_critical),
        nagiosplugin.ScalarContext('responsetime_last_one_hour',
                                   args.response_warning,
                                   args.response_critical),
        nagiosplugin.ScalarContext('responsetime_last_24_hours',
                                   args.response_warning,
                                   args.response_critical),
        nagiosplugin.ScalarContext('remaining_api_calls_hour',
                                   args.apicalls_hour_warning,
                                   args.apicalls_hour_critical),
        nagiosplugin.ScalarContext('remaining_api_calls_day',
                                   args.apicalls_day_warning,
                                   args.apicalls_day_critical),
        nagiosplugin.ScalarContext('script_runtime', ':10'),
        KeynoteSummary(args.measurement_slot)
        )
    check.main(verbose=args.verbose, timeout=args.timeout)


if __name__ == '__main__':
    main()
